### ISSUE TITLE
datasets/prepare_pascal_pp.py

### ISSUE THREAD

**Issue by geek-APTX4869** [tue-mps/tapps#2]
Dear author：
  Using datasets/prepare_pascal_pp.py does not generate the dataset

**Comment by DdeGeus** [comment]
Thank you for your interest in our work!

Could you provide more details about the problem you encounter? Did you follow the dataset preparation instructions that we provide at https://github.com/tue-mps/tapps/blob/master/datasets/README.md? In other words, did you first download the Pascal-PP labels and Pascal VOC 2010 images and then store them in the correct folder structure?
