### ISSUE TITLE
PartSQ PQ

### ISSUE THREAD

**Issue by geek-APTX4869** [tue-mps/tapps#4]
Dear author：
  How to calculate the PartSQ and PQ?

**Comment by DdeGeus** [comment]
The instructions for evaluation are provided here: https://github.com/tue-mps/tapps?tab=readme-ov-file#evaluation

After the model is trained, its PartPQ and PartSQ can be calculated by following two steps:
1. [Run the model on the validation set, and output the predictions.](https://github.com/tue-mps/tapps?tab=readme-ov-file#1-making-predictions-and-saving-them)
2. [Run the evaluation script by providing the directory where the predictions are stored.](https://github.com/tue-mps/tapps?tab=readme-ov-file#2-evaluating-the-predictions-and-calculating-the-partpq)

This will return the PartPQ and PartSQ scores.

Does this work for you?

**Comment by geek-APTX4869** [comment]
In fact, `eval/eval_partpq.py` can only output `PartPQ_Pt`，`PartPQ_No Pt`，`PartPQ_All`

**Comment by DdeGeus** [comment]
In the `/PATH/WHERE/PREDICTIONS/ARE/STORED/` directory, which is given as an input to `eval_partpq.py` with the `--save_dir` flag, the evaluation script will create a `results` folder, in which it will store a .json file with more detailed results. This includes per-class PartPQ scores, the overall PartSQ results and more. So you can find the **PartSQ** scores here.

As for the **PQ**, this will be evaluated when conducting the first step of the evaluation process, i.e., [running the model on the validation set](https://github.com/tue-mps/tapps/tree/master?tab=readme-ov-file#1-making-predictions-and-saving-them). The PQ will be an output of the script.

Could you check if this is also the case for you?

**Comment by geek-APTX4869** [comment]
Thanks，after your guidance, I found these results
