### ISSUE TITLE
table3

### ISSUE THREAD

**Issue by geek-APTX4869** [tue-mps/tapps#5]
Dear author：
  How to get results of the table3？

**Comment by DdeGeus** [comment]
The highlighted rows in Tab. 3 of the paper show the results for the default configuration of TAPPS, where we predict only compatible parts for each object query during training and testing. Therefore, these results can be obtained with the default configuration files provided in this repository.

The other results in Tab. 3 (predicting also incompatible parts during training and/or testing), have been obtained with an earlier, experimental codebase. These configurations are not directly available in this public repository. In other words, to get these results, you need to change the code manually. 

To also predict incompatible parts during inference, the `pps_inference` [function](https://github.com/tue-mps/tapps/blob/master/tapps/maskformer_model.py#L537)  in `maskformer_model.py` needs to be adapted. Among others, the number of parts per query (`num_parts_per_query`) and the part ids per query (`part_ids_per_query`) need to be changed to contain all parts.

To also predict incompatible parts during training, similar changes need to be made in the `loss_masks_parts` [function](https://github.com/tue-mps/tapps/blob/master/tapps/modeling/criterion.py#L147) in `criterion.py`.
